// Auto-generated by tools/build_richer_snapshot.py.
// Supplemental data for the new track-timeline and volunteer
// recognition sections. Sits next to snapshot.js, doesn't
// replace it. The existing dashboard keeps reading
// window.TVF_PUBLIC_DATA; the new sections read TVF_ROSTER.
window.TVF_ROSTER = {
  "generatedAt": "2026-05-17T20:33:56.859445Z",
  "source": {
    "name": "Tarih Vakfı Gönüllü Ağı (genişletilmiş)",
    "rosterSize": 59,
    "bioSize": 24,
    "workplanBoxes": 86
  },
  "cumulative": {
    "sessions": 76,
    "activeVolunteers": 23,
    "rosterVolunteers": 62,
    "tracks": 9,
    "targetPages": 72465,
    "targetBelge": 11638,
    "monthsActive": 5,
    "firstActivityDate": "2026-01",
    "latestActivityDate": "2026-05"
  },
  "tracks": [
    {
      "key": "tarama",
      "label": "Tarama (belge & kartpostal)",
      "color": "#601040",
      "sessions": 23,
      "people": [
        "Arda Tuzkapı",
        "Ateş Dağlı",
        "Aysu Balta",
        "Betül İşeri",
        "Kadir Ağaç",
        "Kübra Başpınar",
        "Lara Gülmez",
        "Sibel Dağ",
        "Çiğdem Külçür Özgören",
        "Özgün Çağatay Günel"
      ],
      "peopleCount": 10,
      "byMonth": {
        "2026-03": 2,
        "2026-04": 9,
        "2026-05": 12
      }
    },
    {
      "key": "envanter",
      "label": "Envanter (afiş, görsel-işitsel)",
      "color": "#8a2a62",
      "sessions": 24,
      "people": [
        "Aysu Balta",
        "Beşir Özmen",
        "Duygu Polat",
        "Gülistan Eren",
        "Hacer Er",
        "Lara Gülmez",
        "Mine Karataş",
        "Tuğrulhan Ata Türkel",
        "İlknur Arslan"
      ],
      "peopleCount": 9,
      "byMonth": {
        "2026-04": 14,
        "2026-05": 10
      }
    },
    {
      "key": "kurumsal_bellek",
      "label": "Kurum belleği (karar def., G.K.)",
      "color": "#3b6d11",
      "sessions": 7,
      "people": [
        "Eray Yılmaz",
        "Çiğdem Külçür Özgören"
      ],
      "peopleCount": 2,
      "byMonth": {
        "2026-01": 1,
        "2026-02": 3,
        "2026-03": 1,
        "2026-05": 2
      }
    },
    {
      "key": "osmanlica",
      "label": "Osmanlıca çeviri",
      "color": "#BA7517",
      "sessions": 1,
      "people": [
        "Günay Kayarlar"
      ],
      "peopleCount": 1,
      "byMonth": {
        "2026-04": 1
      }
    },
    {
      "key": "proje_basvuru",
      "label": "Proje başvurusu (Gerda Henkel)",
      "color": "#0c447c",
      "sessions": 2,
      "people": [
        "Gülistan Eren"
      ],
      "peopleCount": 1,
      "byMonth": {
        "2026-04": 1,
        "2026-05": 1
      }
    },
    {
      "key": "egitim",
      "label": "Eğitim (İş Bankası Müzesi)",
      "color": "#534AB7",
      "sessions": 2,
      "people": [
        "Arda Tuzkapı",
        "Beşir Özmen"
      ],
      "peopleCount": 2,
      "byMonth": {
        "2026-04": 2
      }
    },
    {
      "key": "ars_web",
      "label": "Arşiv-web & IT",
      "color": "#444441",
      "sessions": 3,
      "people": [
        "Arif Solmaz"
      ],
      "peopleCount": 1,
      "byMonth": {
        "2026-04": 1,
        "2026-05": 2
      }
    },
    {
      "key": "koordinasyon",
      "label": "Koordinasyon & planlama",
      "color": "#888780",
      "sessions": 2,
      "people": [
        "Gülistan Eren",
        "Sevda Akın"
      ],
      "peopleCount": 2,
      "byMonth": {
        "2026-04": 1,
        "2026-05": 1
      }
    },
    {
      "key": "diger",
      "label": "Diğer",
      "color": "#74686e",
      "sessions": 12,
      "people": [
        "Arda Tuzkapı",
        "Cemil Akın",
        "Gülistan Eren",
        "Kübra Başpınar",
        "Neşe Gürses",
        "Sibel Dağ"
      ],
      "peopleCount": 6,
      "byMonth": {
        "2026-04": 1,
        "2026-05": 11
      }
    }
  ],
  "volunteers": [
    {
      "name": "Gülistan Eren",
      "slug": "gulistan-eren",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 13,
      "tracks": [
        "diger",
        "envanter",
        "koordinasyon",
        "proje_basvuru"
      ],
      "byMonth": {
        "2026-04": 4,
        "2026-05": 9
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-14",
      "active": true,
      "log": [
        {
          "date": "2026-05-14",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-13",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-12",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-11",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-08",
          "track": "proje_basvuru",
          "calisma": "Gerda Henkel, PNB Planlama",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Lenovo"
        },
        {
          "date": "2026-05-07",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-06",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-05",
          "track": "envanter",
          "calisma": "",
          "devam": "Arşiv toparlama, envanter çalışması, Varol Saydam PNB toplantı.",
          "notes": "",
          "scanner": "",
          "computer": "Lenovo"
        },
        {
          "date": "2026-05-04",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Lenovo"
        },
        {
          "date": "2026-04-30",
          "track": "envanter",
          "calisma": "Gerda Henkel Proje Başvuru Hazırlığı",
          "devam": "Envanter listesi hazırlığı.",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi 1"
        },
        {
          "date": "2026-04-29",
          "track": "koordinasyon",
          "calisma": "Karma Çalışma",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-28",
          "track": "envanter",
          "calisma": "Gerda Henkel Proje Başvuru Hazırlığı",
          "devam": "Envanter listesi hazırlığı.",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-27",
          "track": "proje_basvuru",
          "calisma": "Gerda Henkel Proje Başvuru Hazırlığı",
          "devam": "Toplantı",
          "notes": "Varol Sayfam, Gülay Kayacan Toplantı\nProje grubu ikinci toplantı.",
          "scanner": "",
          "computer": "Şahsi 3"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Çiğdem Külçür Özgören",
      "slug": "cigdem-kulcur-ozgoren",
      "city": "İstanbul",
      "role": "Doktora Öğrencisi/ Öğretim Görevlisi",
      "tv_role": "Gönüllü",
      "uni": "Kocaeli Üniversitesi",
      "dept": "Atatürk İlkeleri ve İnkılapları Bölümü",
      "topics": [],
      "slots": [
        "Çar-1",
        "Çar-2"
      ],
      "sessions": 13,
      "tracks": [
        "kurumsal_bellek",
        "tarama"
      ],
      "byMonth": {
        "2026-01": 1,
        "2026-02": 3,
        "2026-03": 3,
        "2026-04": 4,
        "2026-05": 2
      },
      "scanners": [
        "Visan"
      ],
      "boxes": [],
      "firstSeen": "2026-01-28",
      "lastSeen": "2026-05-15",
      "active": true,
      "log": [
        {
          "date": "2026-05-15",
          "track": "kurumsal_bellek",
          "calisma": "Genel Kurul 2013-2015-2017-2019 Dosyası Dijitalleştirme, 7. ve 8. Genel Kurul Toplantısı Dijitalleştirilmesi.",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-06",
          "track": "kurumsal_bellek",
          "calisma": "Genel Kurul 2013-2015-2017-2019 Dosyası Dijitalleştirme",
          "devam": "",
          "notes": "Dosya Dijitalleştirildi.",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-29",
          "track": "tarama",
          "calisma": "5. Olağan Genel Kurul Dosyası Tarama",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-15",
          "track": "tarama",
          "calisma": "4. Olağan Genel Kurul Dostası Tarama",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-08",
          "track": "tarama",
          "calisma": "3. Olağan Genel Kurul  Dosyası Tarama",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-01",
          "track": "tarama",
          "calisma": "1. Olağan Genel Kurul Dosyası Tarama",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "Visan",
          "computer": ""
        },
        {
          "date": "2026-03-25",
          "track": "tarama",
          "calisma": "2. Olağan Genel Kurul Dosyası Tarama",
          "devam": "",
          "notes": "Dosya dijitalleştirildi.",
          "scanner": "Visan",
          "computer": ""
        },
        {
          "date": "2026-03-14",
          "track": "tarama",
          "calisma": "0001, TVA .01.00 Vakıf Kuruluşu/ Girişim Dosyası Dijitalleştirme, 3. Olağan Kurul Dosyası Taraması Başladı",
          "devam": "3. Olağan Genel Kurul Dosyası Taranması",
          "notes": "Dosya bir bölümü başka bir gönüllü tarafından tarandı.",
          "scanner": "Visan",
          "computer": ""
        },
        {
          "date": "2026-03-04",
          "track": "kurumsal_bellek",
          "calisma": "TV Karar Defterlerinden malzemenin Kronolojiye Yüklenmesi",
          "devam": "",
          "notes": "Vakıf Kurucu ve Üyeleri, Başkanları Kronolojiye Yüklendi.",
          "scanner": "Visan",
          "computer": ""
        },
        {
          "date": "2026-02-20",
          "track": "kurumsal_bellek",
          "calisma": "Tarih Vakfı Karar Defterlerinin Dijitalleştirilmesi",
          "devam": "Karar Defterlerinden malzemeyi TV Kronolojisine yükleme",
          "notes": "Faaliyet Raporlarından ve İç Karar Defterlerinden malzeme TV Kronolojisine kaydedildi.",
          "scanner": "Visan",
          "computer": ""
        },
        {
          "date": "2026-02-18",
          "track": "kurumsal_bellek",
          "calisma": "Tv Kronolojisi",
          "devam": "Toplumsal Tarih Dergisi Dosya Adlarının Excel dosyasına kayıt edilmesi",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi"
        },
        {
          "date": "2026-02-05",
          "track": "kurumsal_bellek",
          "calisma": "Arşiv Komisyonu Toplantısı",
          "devam": "TV Kronolojisi",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi"
        },
        {
          "date": "2026-01-28",
          "track": "kurumsal_bellek",
          "calisma": "TV Kronolojisi için Plan Toplantısı",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Lara Gülmez",
      "slug": "lara-gulmez",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Dijitalleştirme",
        "Web Sitesi Alt Yapısı"
      ],
      "slots": [
        "Pzt-1",
        "Pzt-2",
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 9,
      "tracks": [
        "envanter",
        "tarama"
      ],
      "byMonth": {
        "2026-04": 3,
        "2026-05": 6
      },
      "scanners": [
        "Viisan s21"
      ],
      "boxes": [
        "16"
      ],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-13",
      "active": true,
      "log": [
        {
          "date": "2026-05-13",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Kutu 16",
          "notes": "16. kutunun 2.dosyasından 62 belge tarandı",
          "scanner": "Viisan s21",
          "computer": "Şahsi 1"
        },
        {
          "date": "2026-05-12",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Afiş B Dolabı Tamamlandı",
          "scanner": "",
          "computer": "HP"
        },
        {
          "date": "2026-05-11",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Afiş Dolabı",
          "scanner": "",
          "computer": "HP"
        },
        {
          "date": "2026-05-06",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Afiş Dolabı",
          "scanner": "",
          "computer": "HP"
        },
        {
          "date": "2026-05-05",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Afiş Dolabı",
          "scanner": "",
          "computer": "HP"
        },
        {
          "date": "2026-05-04",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Afiş Dolabı",
          "scanner": "",
          "computer": "HP"
        },
        {
          "date": "2026-04-29",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Format bazlı görsel-işitsel materyal sayımı(plak)",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-28",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Format bazlı görsel-işitsel materyal sayımı(plaklar hariç)",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-27",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Afiş envanteri",
          "notes": "A dolabı tamamlandı.",
          "scanner": "",
          "computer": "Şahsi 1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Aysu Balta",
      "slug": "aysu-balta",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "İstanbul Üniversitesi",
      "dept": "Latin Dili ve Edebiyatı",
      "topics": [
        "Görsel İşitsel Envanter",
        "Dijitalleştirme"
      ],
      "slots": [
        "Pzt-1",
        "Pzt-2",
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 8,
      "tracks": [
        "envanter",
        "tarama"
      ],
      "byMonth": {
        "2026-04": 3,
        "2026-05": 5
      },
      "scanners": [
        "Epson"
      ],
      "boxes": [
        "2"
      ],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-12",
      "active": true,
      "log": [
        {
          "date": "2026-05-12",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Sözlü Tarih Kayıt Süreleri Hesaplanması Tamamlandı",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-05-11",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB kartpostal kutu 2",
          "notes": "40 adet kartpostal tarandı (40/138)",
          "scanner": "Epson",
          "computer": "Müze"
        },
        {
          "date": "2026-05-06",
          "track": "envanter",
          "calisma": "",
          "devam": "Görsel işitsel envanter",
          "notes": "Gürel Tüzün'den alınan dijitalleştirimiş malzemelerin envanteri ve yüklenmesi",
          "scanner": "",
          "computer": "Dell ve Şahsi 1"
        },
        {
          "date": "2026-05-05",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Dell ve Şahsi 1"
        },
        {
          "date": "2026-05-04",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Görsel-işitsel malzemeden istenen fonların envanteri",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-29",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Format bazlı görsel-işitsel materyal sayımı(plak)",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-28",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "Format bazlı görsel-işitsel materyal sayımı(plaklar hariç)",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-27",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "TBCT envanter tamamlandı.",
          "scanner": "",
          "computer": "Şahsi 2"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Arda Tuzkapı",
      "slug": "arda-tuzkap",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 6,
      "tracks": [
        "diger",
        "egitim",
        "tarama"
      ],
      "byMonth": {
        "2026-04": 3,
        "2026-05": 3
      },
      "scanners": [
        "BookEye",
        "Bookeye",
        "Canon"
      ],
      "boxes": [
        "20"
      ],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-11",
      "active": true,
      "log": [
        {
          "date": "2026-05-11",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "Defter kodlama, Kutu 20 ve 21 kontrol ve tamamlama",
          "notes": "Kutu 20'nin içindeki beş defterden üçünün kontrolü ve kodlaması yapıldı.",
          "scanner": "Bookeye",
          "computer": "Müze"
        },
        {
          "date": "2026-05-06",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-05",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Müze"
        },
        {
          "date": "2026-04-29",
          "track": "egitim",
          "calisma": "Tarama",
          "devam": "Tarama Eğitimi(İş Bankası Müzesi)",
          "notes": "",
          "scanner": "BookEye",
          "computer": "Müze"
        },
        {
          "date": "2026-04-28",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-04-27",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Fotoraf-2",
          "notes": "2. fotoğraf kutusu tamamlandı. Kodlama ve kontrol ile devam edecek.",
          "scanner": "Canon",
          "computer": "HP 1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Arif Solmaz",
      "slug": "arif-solmaz",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Teknik Destek",
        "Dijitalleştirme"
      ],
      "slots": [
        "Sal-1",
        "Sal-2",
        "Cum-1",
        "Cum-2"
      ],
      "sessions": 3,
      "tracks": [
        "ars_web"
      ],
      "byMonth": {
        "2026-04": 1,
        "2026-05": 2
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-29",
      "lastSeen": "2026-05-15",
      "active": true,
      "log": [
        {
          "date": "2026-05-15",
          "track": "ars_web",
          "calisma": "Web Sitesi",
          "devam": "Web sitesi güncelleme",
          "notes": "Gönüllü işlerini özetleyen web sitesi üzerinde çalışmalar yapıldı. Siteye tarihvakfi.github.io üzerinden erişilebiliyor",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-06",
          "track": "ars_web",
          "calisma": "Arşiv - Web",
          "devam": "PNB Dosya Arşivi",
          "notes": "Disk içindeki PBN ile ilgili olduğu belirlenen tüm arşiv dosyaları içeriklerine göre sınıflandırıldı ve E:\\PNB_arifsolmaz_060526 konumuna kaydedildi",
          "scanner": "",
          "computer": "Dell"
        },
        {
          "date": "2026-04-29",
          "track": "ars_web",
          "calisma": "Arşiv - Web",
          "devam": "PNB Dosya Arşivi",
          "notes": "Harici disk içindeki eski arşiv dosyalarının kategorize edilmesi.",
          "scanner": "",
          "computer": "Dell"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Kübra Başpınar",
      "slug": "kubra-basp-nar",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Dijitalleştirme"
      ],
      "slots": [
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 3,
      "tracks": [
        "diger",
        "tarama"
      ],
      "byMonth": {
        "2026-04": 1,
        "2026-05": 2
      },
      "scanners": [
        "Epson"
      ],
      "boxes": [],
      "firstSeen": "2026-04-29",
      "lastSeen": "2026-05-06",
      "active": true,
      "log": [
        {
          "date": "2026-05-06",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        },
        {
          "date": "2026-05-05",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Müze"
        },
        {
          "date": "2026-04-29",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Dia tarama",
          "notes": "100 dia tarandı",
          "scanner": "Epson",
          "computer": "Müze"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Sibel Dağ",
      "slug": "sibel-dag",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 3,
      "tracks": [
        "diger",
        "tarama"
      ],
      "byMonth": {
        "2026-04": 1,
        "2026-05": 2
      },
      "scanners": [
        "Viisan A3 Flat",
        "Viisan s21"
      ],
      "boxes": [
        "16",
        "tarama"
      ],
      "firstSeen": "2026-04-28",
      "lastSeen": "2026-05-12",
      "active": true,
      "log": [
        {
          "date": "2026-05-12",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB kutu 16 - halk siiri",
          "notes": "1.dosya tamamlandı - 200 sayfa",
          "scanner": "Viisan s21",
          "computer": "Şahsi 1"
        },
        {
          "date": "2026-05-05",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB 68.kutu tarama devam",
          "notes": "70 sayfalık tarama (Kutu 68 içindeki 1-2-3-4 ve 10. zarf tamamlandı 5.zarf bitmedi)",
          "scanner": "Viisan A3 Flat",
          "computer": "HP2"
        },
        {
          "date": "2026-04-28",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Ateş Dağlı",
      "slug": "ates-dagl",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Pzt-1",
        "Pzt-2"
      ],
      "sessions": 2,
      "tracks": [
        "tarama"
      ],
      "byMonth": {
        "2026-04": 1,
        "2026-05": 1
      },
      "scanners": [
        "Viisan s21"
      ],
      "boxes": [
        "15"
      ],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-04",
      "active": true,
      "log": [
        {
          "date": "2026-05-04",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Belge",
          "notes": "Kutu 15 taramasına devam. 305 sayfa tarandı",
          "scanner": "Viisan s21",
          "computer": "Şahsi 1"
        },
        {
          "date": "2026-04-27",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Belge",
          "notes": "Kutu 15 taraması başladı. 212",
          "scanner": "Viisan s21",
          "computer": "Dell"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Betül İşeri",
      "slug": "betul-iseri",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 2,
      "tracks": [
        "tarama"
      ],
      "byMonth": {
        "2026-04": 1,
        "2026-05": 1
      },
      "scanners": [
        "Viisan A3 Flat"
      ],
      "boxes": [
        "14"
      ],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-05-04",
      "active": true,
      "log": [
        {
          "date": "2026-05-04",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Belge",
          "notes": "Kutu 14 tarama devam. sayfa sayısı 197",
          "scanner": "Viisan A3 Flat",
          "computer": "HP 2"
        },
        {
          "date": "2026-04-27",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB Belge",
          "notes": "Kutu 14 tarama devam. 136 sayfa",
          "scanner": "Viisan A3 Flat",
          "computer": "HP 2"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Beşir Özmen",
      "slug": "besir-ozmen",
      "city": "İstanbul",
      "role": "Sys Danışmanlık Ortağı",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Pzt-1",
        "Pzt-2",
        "Çar-1",
        "Çar-2",
        "Cum-1",
        "Cum-2"
      ],
      "sessions": 2,
      "tracks": [
        "egitim",
        "envanter"
      ],
      "byMonth": {
        "2026-04": 2
      },
      "scanners": [
        "BookEye"
      ],
      "boxes": [],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-04-29",
      "active": true,
      "log": [
        {
          "date": "2026-04-29",
          "track": "egitim",
          "calisma": "Tarama",
          "devam": "Tarama Eğitimi(İş Bankası Müzesi)",
          "notes": "",
          "scanner": "BookEye",
          "computer": "Müze"
        },
        {
          "date": "2026-04-27",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Görsel işitsel envanter",
          "notes": "TBCT envanter tamamlandı.",
          "scanner": "",
          "computer": "Şahsi 2"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Eray Yılmaz",
      "slug": "eray-y-lmaz",
      "city": "İstanbul",
      "role": "Öğretim Görevlisi",
      "tv_role": "Gönüllü",
      "uni": "Yıldız Teknik",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 2,
      "tracks": [
        "kurumsal_bellek"
      ],
      "byMonth": {
        "2026-01": 1,
        "2026-02": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-01-28",
      "lastSeen": "2026-02-05",
      "active": true,
      "log": [
        {
          "date": "2026-02-05",
          "track": "kurumsal_bellek",
          "calisma": "Arşiv Komisyonu Toplantısı",
          "devam": "TV Kronolojisi",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi"
        },
        {
          "date": "2026-01-28",
          "track": "kurumsal_bellek",
          "calisma": "TV Kronolojisi için Plan Toplantısı",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": "Şahsi"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Kadir Ağaç",
      "slug": "kadir-agac",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Cum-1",
        "Cum-2"
      ],
      "sessions": 2,
      "tracks": [
        "tarama"
      ],
      "byMonth": {
        "2026-05": 2
      },
      "scanners": [
        "Canon"
      ],
      "boxes": [
        "1"
      ],
      "firstSeen": "2026-05-08",
      "lastSeen": "2026-05-15",
      "active": true,
      "log": [
        {
          "date": "2026-05-15",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB kartpostal kutu 1",
          "notes": "PNB kartpostal kutu 1 bitti. (39/149) adet kartpostal tarandı.",
          "scanner": "Canon",
          "computer": "HP1"
        },
        {
          "date": "2026-05-08",
          "track": "tarama",
          "calisma": "Tarama",
          "devam": "PNB kartpostal kutu 1",
          "notes": "PNB kartpostal kutu 1 devam. (60/149) adet kartpostal tarandı.",
          "scanner": "Canon",
          "computer": "HP1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Cemil Akın",
      "slug": "cemil-ak-n",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Osmanlıca"
      ],
      "slots": [
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 1,
      "tracks": [
        "diger"
      ],
      "byMonth": {
        "2026-05": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-05-05",
      "lastSeen": "2026-05-05",
      "active": true,
      "log": [
        {
          "date": "2026-05-05",
          "track": "diger",
          "calisma": "",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Duygu Polat",
      "slug": "duygu-polat",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 1,
      "tracks": [
        "envanter"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-04-27",
      "active": true,
      "log": [
        {
          "date": "2026-04-27",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Afiş envanteri",
          "notes": "A dolabı tamamlandı.",
          "scanner": "",
          "computer": "Şahsi 1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Günay Kayarlar",
      "slug": "gunay-kayarlar",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 1,
      "tracks": [
        "osmanlica"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-30",
      "lastSeen": "2026-04-30",
      "active": true,
      "log": [
        {
          "date": "2026-04-30",
          "track": "osmanlica",
          "calisma": "Çeviri(Osmanlıca)",
          "devam": "",
          "notes": "Cemil Bey'in çevirileri kontrol(fermanlar)",
          "scanner": "",
          "computer": ""
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Hacer Er",
      "slug": "hacer-er",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Osmanlıca"
      ],
      "slots": [
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 1,
      "tracks": [
        "envanter"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-27",
      "lastSeen": "2026-04-27",
      "active": true,
      "log": [
        {
          "date": "2026-04-27",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "AŞE Osmanlıca defter tanımlama",
          "notes": "Ahmet Şükrü Esen Osmanlıca defter tanımlama devam.",
          "scanner": "",
          "computer": "Lenovo"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Mine Karataş",
      "slug": "mine-karatas",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 1,
      "tracks": [
        "envanter"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-29",
      "lastSeen": "2026-04-29",
      "active": true,
      "log": [
        {
          "date": "2026-04-29",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Afiş envanteri",
          "notes": "Harita çekmecesinin envanteri çıkarıldı",
          "scanner": "",
          "computer": "Şahsi 1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Neşe Gürses",
      "slug": "nese-gurses",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 1,
      "tracks": [
        "diger"
      ],
      "byMonth": {
        "2026-05": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-05-06",
      "lastSeen": "2026-05-06",
      "active": true,
      "log": [
        {
          "date": "2026-05-06",
          "track": "diger",
          "calisma": "",
          "devam": "Kadın Eserleri Kütüphanesi",
          "notes": "",
          "scanner": "",
          "computer": ""
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Sevda Akın",
      "slug": "sevda-ak-n",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Teknik Destek",
        "Dokümantasyon Sistemi"
      ],
      "slots": [
        "Sal-1",
        "Sal-2",
        "Cum-1"
      ],
      "sessions": 1,
      "tracks": [
        "koordinasyon"
      ],
      "byMonth": {
        "2026-05": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-05-08",
      "lastSeen": "2026-05-08",
      "active": true,
      "log": [
        {
          "date": "2026-05-08",
          "track": "koordinasyon",
          "calisma": "PNB Planlama, Raporlama",
          "devam": "",
          "notes": "",
          "scanner": "",
          "computer": ""
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Tuğrulhan Ata Türkel",
      "slug": "tugrulhan-ata-turkel",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 1,
      "tracks": [
        "envanter"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-30",
      "lastSeen": "2026-04-30",
      "active": true,
      "log": [
        {
          "date": "2026-04-30",
          "track": "envanter",
          "calisma": "Envanter",
          "devam": "Datasafe Excel Düzenleme",
          "notes": "",
          "scanner": "",
          "computer": "Dell"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Özgün Çağatay Günel",
      "slug": "ozgun-cagatay-gunel",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Pzt-1",
        "Pzt-2"
      ],
      "sessions": 1,
      "tracks": [
        "tarama"
      ],
      "byMonth": {
        "2026-05": 1
      },
      "scanners": [
        "Viisan s21"
      ],
      "boxes": [
        "tarama"
      ],
      "firstSeen": "2026-05-04",
      "lastSeen": "2026-05-04",
      "active": true,
      "log": [
        {
          "date": "2026-05-04",
          "track": "tarama",
          "calisma": "Tarama ve Osmanlıca çeviri",
          "devam": "PNB 15 kutu tarama ve harita envanteri Osmanlıca çeviri",
          "notes": "Kutu 15 devam",
          "scanner": "Viisan s21",
          "computer": "Şahsi 1"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "İlknur Arslan",
      "slug": "ilknur-arslan",
      "city": "İstanbul",
      "role": "Emekli",
      "tv_role": "Gönüllü",
      "uni": "Marmara Üniversitesi",
      "dept": "İletişim Fakültesi",
      "topics": [],
      "slots": [
        "Pzt-1",
        "Pzt-2",
        "Sal-1",
        "Sal-2"
      ],
      "sessions": 1,
      "tracks": [
        "envanter"
      ],
      "byMonth": {
        "2026-04": 1
      },
      "scanners": [],
      "boxes": [],
      "firstSeen": "2026-04-30",
      "lastSeen": "2026-04-30",
      "active": true,
      "log": [
        {
          "date": "2026-04-30",
          "track": "envanter",
          "calisma": "Gerda Henkel Proje Başvuru Hazırlığı",
          "devam": "Envanter listesi hazırlığı.",
          "notes": "",
          "scanner": "",
          "computer": "Lenovo"
        }
      ],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Ahmet Turan",
      "slug": "ahmet-turan",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Arda Turgut Çapraz",
      "slug": "arda-turgut-capraz",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "TEVİTÖL",
      "dept": "",
      "topics": [
        "Dijitalleştirme"
      ],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Aylin Aktaş",
      "slug": "aylin-aktas",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Betül Ayşe İşeri",
      "slug": "betul-ayse-iseri",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Gönüllü Koordinasyonu"
      ],
      "slots": [
        "Pzt-1",
        "Pzt-2"
      ],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Büşra Aydın",
      "slug": "busra-ayd-n",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Ceren Nur Çakmak",
      "slug": "ceren-nur-cakmak",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "Boğaziçi Üniversitesi",
      "dept": "Türk Dili ve Edebiyatı 2. sınıf öğrencisi",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Damla Durlu",
      "slug": "damla-durlu",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "Boğaziçi Üniversitesi",
      "dept": "Tarih Bölümü",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Eda Garip",
      "slug": "eda-garip",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Edanur Şekercioğlu",
      "slug": "edanur-sekercioglu",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Emine Melike Sezer",
      "slug": "emine-melike-sezer",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "Bilgi",
      "dept": "Tarih Bölümü",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Emirhan Çuhadar",
      "slug": "emirhan-cuhadar",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Erdem Topkar",
      "slug": "erdem-topkar",
      "city": "İstanbul",
      "role": "Aretias Sigorta",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Eylül Ener",
      "slug": "eylul-ener",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Eylül Kaya",
      "slug": "eylul-kaya",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Fatma Yalçın",
      "slug": "fatma-yalc-n",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Feyza Daloglu",
      "slug": "feyza-daloglu",
      "city": "İstanbul",
      "role": "Doktora Öğrencisi",
      "tv_role": "Gönüllü",
      "uni": "ODTÜ",
      "dept": "Mimarlık",
      "topics": [
        "Mimari Projeler Envanteri"
      ],
      "slots": [
        "Cum-1",
        "Cum-2"
      ],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Hakan Yıldız",
      "slug": "hakan-y-ld-z",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Hayal Fefer",
      "slug": "hayal-fefer",
      "city": "İstanbul",
      "role": "Emekli, Yönetici",
      "tv_role": "Gönüllü",
      "uni": "Marmara İletişim Mezunu",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Kaan Kemal Yazıcı",
      "slug": "kaan-kemal-yaz-c",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Leyla Diana Gücük",
      "slug": "leyla-diana-gucuk",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Mehmet Akif Top",
      "slug": "mehmet-akif-top",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Mehmet Daraoğlu",
      "slug": "mehmet-daraoglu",
      "city": "İstanbul",
      "role": "Emekli",
      "tv_role": "Gönüllü",
      "uni": "İstanbul Üniversitesi",
      "dept": "İktisat",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Mehmet Satıcı",
      "slug": "mehmet-sat-c",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Mehmet Zahid Balcı",
      "slug": "mehmet-zahid-balc",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Neslihan Erken",
      "slug": "neslihan-erken",
      "city": "İstanbul",
      "role": "Öğretim Görevlisi",
      "tv_role": "Gönüllü",
      "uni": "Yıldız Teknik",
      "dept": "",
      "topics": [
        "Dijital Envanter"
      ],
      "slots": [
        "Çar-2"
      ],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Ozan Eren Üçgül",
      "slug": "ozan-eren-ucgul",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Selin Ayan Avunduk",
      "slug": "selin-ayan-avunduk",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Sena Yiğit",
      "slug": "sena-yigit",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Tunahan Çelen",
      "slug": "tunahan-celen",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Tülin Er",
      "slug": "tulin-er",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Dijitalleştirme"
      ],
      "slots": [
        "Per-1",
        "Per-2"
      ],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Yasemin Dağdaş",
      "slug": "yasemin-dagdas",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [
        "Arşivcilik"
      ],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Yurdanur Kaur",
      "slug": "yurdanur-kaur",
      "city": "İstanbul",
      "role": "Emekli",
      "tv_role": "Gönüllü",
      "uni": "AÜ SBF",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Yılmaz Efe Çetinyürek",
      "slug": "y-lmaz-efe-cetinyurek",
      "city": "İstanbul",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Zeynep Eraslan",
      "slug": "zeynep-eraslan",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Zinnur Acar",
      "slug": "zinnur-acar",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Öykü Demirbaş",
      "slug": "oyku-demirbas",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "TEVİTÖL",
      "dept": "",
      "topics": [
        "Web Sitesi Alt Yapısı"
      ],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Özgen Kaybaki",
      "slug": "ozgen-kaybaki",
      "city": "Ankara",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "İrfan Akça",
      "slug": "irfan-akca",
      "city": "İstanbul",
      "role": "Öğrenci",
      "tv_role": "Gönüllü",
      "uni": "İstanbul Bilgi Üniversitesi",
      "dept": "",
      "topics": [],
      "slots": [],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    },
    {
      "name": "Şehide Arman",
      "slug": "sehide-arman",
      "city": "",
      "role": "",
      "tv_role": "Gönüllü",
      "uni": "",
      "dept": "",
      "topics": [],
      "slots": [
        "Cum-1",
        "Cum-2"
      ],
      "sessions": 0,
      "tracks": [],
      "byMonth": {},
      "scanners": [],
      "boxes": [],
      "firstSeen": null,
      "lastSeen": null,
      "active": false,
      "log": [],
      "bio": {
        "narrative": "",
        "shortRole": "",
        "tvNarrative": "",
        "website": "",
        "twitter": "",
        "linkedin": "",
        "github": "",
        "orcid": "",
        "scholar": "",
        "email": ""
      }
    }
  ],
  "monthsActive": [
    "2026-01",
    "2026-02",
    "2026-03",
    "2026-04",
    "2026-05"
  ]
};
