import{auth,db,provider,signInWithPopup,signOut,onAuthStateChanged,serverTimestamp,missingConfigMessage}from"../js/firebase-init.js";
import{collection,addDoc,doc,getDoc,getDocs,setDoc,deleteDoc,query,orderBy,where,limit,updateDoc}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import{escapeHTML,formatDate,badge}from"../js/helpers.js";
var cu=null,cp=null,rd={},pi=[],allUsers=[];
var ld=document.getElementById("loadingState"),tb=document.getElementById("tabBar"),hu=document.getElementById("headerUser");
function sw(n){document.querySelectorAll(".tab").forEach(function(t){t.classList.toggle("active",t.dataset.tab===n)});document.querySelectorAll(".tab-content").forEach(function(c){c.classList.toggle("hidden",c.id!=="tab-"+n)})}
tb?.addEventListener("click",function(e){var t=e.target.closest(".tab");if(t)sw(t.dataset.tab)});
document.getElementById("signOutBtn")?.addEventListener("click",async function(){if(auth)await signOut(auth);window.location.href="../auth/"});
document.getElementById("deleteAccountBtn")?.addEventListener("click",async function(){if(!cu||!db)return;if(!confirm("Hesabınız kalıcı olarak silinecek. Emin misiniz?"))return;if(!confirm("Bu işlem geri alınamaz. Devam etmek istiyor musunuz?"))return;try{await deleteDoc(doc(db,"users",cu.uid));await signOut(auth);window.location.href="../auth/"}catch(err){alert("Hata: "+err.message)}});
function pl(v){return(v||"").split("\n").map(function(l){return l.trim()}).filter(function(l){return l})}
function td(){var d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function ci(file){return new Promise(function(res){var r=new FileReader();r.onload=function(e){var img=new Image();img.onload=function(){var c=document.createElement("canvas"),w=img.width,h=img.height;if(w>800){h=Math.round(h*800/w);w=800}c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);res(c.toDataURL("image/jpeg",0.7))};img.src=e.target.result};r.readAsDataURL(file)})}
function uip(){var el=document.getElementById("imagePreview");if(!el)return;el.innerHTML=pi.map(function(s,i){return'<div class="preview-item"><img src="'+s+'"/><button type="button" class="preview-remove" data-ri="'+i+'">&times;</button></div>'}).join("")}
document.getElementById("reportImageFiles")?.addEventListener("change",async function(e){for(var f of e.target.files){if(f.size>5e6){alert("Maks 5MB: "+f.name);continue}pi.push(await ci(f))}e.target.value="";uip()});
function getSelectedValues(selId){var sel=document.getElementById(selId);if(!sel)return[];return Array.from(sel.selectedOptions).map(function(o){return o.value}).filter(function(v){return v})}
function setSelectedValues(selId,vals){var sel=document.getElementById(selId);if(!sel)return;Array.from(sel.options).forEach(function(o){o.selected=vals.indexOf(o.value)!==-1})}
function findUserName(uid){var u=allUsers.find(function(x){return x.uid===uid});return u?u.data.fullName||u.data.email||uid:""}
function statusLabel(s){var m={submitted:"Gönderildi",revision_needed:"Düzeltme İstendi",approved:"Onaylandı"};return m[s]||s}
function statusClass(s){if(s==="approved")return"badge approved";if(s==="revision_needed")return"badge pending";return"badge"}
function rp(p){return'<div class="profile-card"><div class="profile-avatar">'+escapeHTML((p.fullName||"?")[0].toUpperCase())+'</div><div class="profile-info"><h3>'+escapeHTML(p.fullName||"-")+'</h3><div class="profile-details"><span>'+escapeHTML(p.email||"-")+'</span><span>'+escapeHTML(p.department||"-")+'</span></div><div class="profile-badges">'+badge(p.role||"volunteer")+badge(p.status||"pending")+'</div></div></div>'}
function rt(t,id){var c=t.priority==="high"?"priority-high":t.priority==="low"?"priority-low":"priority-medium";var isA=cp&&(cp.role==="admin"||cp.role==="coordinator");var h='<div class="task-card"><div class="report-header"><strong>'+escapeHTML(t.title||"-")+'</strong>';if(isA)h+='<div class="report-actions"><button class="btn btn-secondary btn-sm" data-et="'+id+'">Düzenle</button><button class="btn btn-block btn-sm" data-dt="'+id+'">Sil</button></div>';h+='</div>'+(t.description?'<div>'+escapeHTML(t.description)+'</div>':'')+'<div class="task-meta"><span class="'+c+'">'+escapeHTML(t.priority||"medium")+'</span><span>'+escapeHTML(t.department||"-")+'</span>'+(t.assignedToEmail?'<span>Atanan: '+escapeHTML(t.assignedToEmail)+'</span>':'')+(t.dueDate?'<span>Son: '+formatDate(t.dueDate)+'</span>':'')+'<span>'+escapeHTML(t.status||"open")+'</span></div></div>';return h}
function rr(r,id){var lk=(r.links||[]).filter(Boolean),im=(r.images||[]).filter(Boolean),own=r.userUid===(cu?cu.uid:""),isA=cp&&(cp.role==="admin"||cp.role==="coordinator");var canEdit=own||isA;var cwUids=r.coworkerUids||[];var cwNames=cwUids.map(function(uid){return findUserName(uid)}).filter(Boolean);var fb=r.feedback||[];var st=r.status||"submitted";var h='<div class="report-card report-'+st+'"><div class="report-header"><strong>'+escapeHTML(r.taskId||"Görev belirtilmedi")+'</strong><div class="report-actions">';if(canEdit)h+='<button class="btn btn-secondary btn-sm" data-er="'+id+'">Düzenle</button><button class="btn btn-block btn-sm" data-dr="'+id+'">Sil</button>';h+='</div></div><div style="margin-top:.35rem">'+escapeHTML(r.summary||"-")+'</div><div style="font-size:.85rem;color:var(--muted);margin-top:.35rem">'+escapeHTML(r.hours||0)+' saat · '+formatDate(r.reportDate)+' · <span class="'+statusClass(st)+'">'+escapeHTML(statusLabel(st))+'</span>'+(r.userUid?' · '+escapeHTML(findUserName(r.userUid)):'')+(cwNames.length?' · Birlikte: '+escapeHTML(cwNames.join(", ")):'')+'</div>';if(st==="revision_needed"&&own){h+='<div class="revision-alert"><strong>Düzeltme istendi</strong><p>Lütfen raporu düzenleyip tekrar gönderin.</p><button class="btn btn-primary btn-sm" data-er="'+id+'">Düzelt ve Tekrar Gönder</button></div>'}if(fb.length){h+='<div class="report-feedback-list">';fb.forEach(function(f){h+='<div class="feedback-item"><strong>'+escapeHTML(f.by||f.reviewerName||"-")+'</strong> <span style="font-size:.8rem;color:var(--muted)">'+escapeHTML(f.date||"")+'</span><div>'+escapeHTML(f.text||f.comment||"")+'</div></div>'});h+='</div>'}if(isA&&st!=="approved"){h+='<div class="report-review-area"><textarea class="review-text" data-review-id="'+id+'" rows="2" placeholder="Geri bildirim yazın..."></textarea><div class="report-actions" style="margin-top:.35rem"><button class="btn btn-approve btn-sm" data-approve="'+id+'">Onayla</button><button class="btn btn-secondary btn-sm" data-revision="'+id+'">Düzeltme İste</button></div></div>'}if(lk.length){h+='<div class="report-links">';lk.forEach(function(l){h+='<a href="'+escapeHTML(l)+'" target="_blank" rel="noopener">'+escapeHTML(l.length>60?l.substring(0,60)+"...":l)+'</a>'});h+='</div>'}if(im.length){h+='<div class="report-images">';im.forEach(function(i){h+='<img src="'+escapeHTML(i)+'" alt="Görsel" loading="lazy" class="lightbox-img"/>'});h+='</div>'}return h+'</div>'}
function ra(a){return'<div class="announce-card"><strong>'+escapeHTML(a.title||"-")+'</strong><div>'+escapeHTML(a.body||"")+'</div><div class="announce-date">'+formatDate(a.createdAt)+' · '+escapeHTML(a.audience||"all")+'</div></div>'}
function rpu(d,u){return'<div class="user-card" id="user-'+u+'"><div class="user-info"><strong>'+escapeHTML(d.fullName||"-")+'</strong><small>'+escapeHTML(d.email||"-")+' · '+escapeHTML(d.department||"-")+'</small></div><div class="user-actions"><button class="btn btn-approve btn-sm" data-action="approve" data-uid="'+u+'">Onayla</button><button class="btn btn-block btn-sm" data-action="block" data-uid="'+u+'">Engelle</button></div></div>'}
function rur(d,u){return'<div class="user-edit-card" id="urow-'+u+'"><div class="form-row"><label>Ad Soyad <input data-fn="'+u+'" value="'+escapeHTML(d.fullName||"")+'" /></label><label>E-posta <input data-em="'+u+'" value="'+escapeHTML(d.email||"")+'" /></label><label>Telefon <input data-ph="'+u+'" value="'+escapeHTML(d.phone||"")+'" /></label></div><div class="form-row"><label>Departman <select data-dp="'+u+'"><option value="">Seçiniz</option><option'+(d.department==="Eğitim"?" selected":"")+'>Eğitim</option><option'+(d.department==="Arşiv"?" selected":"")+'>Arşiv</option><option'+(d.department==="İletişim"?" selected":"")+'>İletişim</option><option'+(d.department==="Etkinlik"?" selected":"")+'>Etkinlik</option><option'+(d.department==="Dijital İçerik"?" selected":"")+'>Dijital İçerik</option></select></label><label>Rol <select data-ru="'+u+'"><option value="volunteer"'+(d.role==="volunteer"?" selected":"")+'>Gönüllü</option><option value="coordinator"'+(d.role==="coordinator"?" selected":"")+'>Koordinatör</option><option value="admin"'+(d.role==="admin"?" selected":"")+'>Yönetici</option></select></label><label>Durum <select data-su="'+u+'"><option value="pending"'+(d.status==="pending"?" selected":"")+'>Beklemede</option><option value="approved"'+(d.status==="approved"?" selected":"")+'>Onaylı</option><option value="blocked"'+(d.status==="blocked"?" selected":"")+'>Engelli</option></select></label></div><div class="form-actions"><button class="btn btn-primary btn-sm" data-sv="'+u+'">Kaydet</button><button class="btn btn-block btn-sm" data-del-user="'+u+'">Sil</button></div></div>'}
async function loadAllUsers(){var s=await getDocs(query(collection(db,"users"),orderBy("createdAt","desc"),limit(200)));allUsers=[];s.docs.forEach(function(d){allUsers.push({uid:d.id,data:d.data()})});var sels=[{id:"reportForUser",def:"Kendim için",exSelf:true},{id:"reportCoworker",def:null,exSelf:true}];sels.forEach(function(cfg){var sel=document.getElementById(cfg.id);if(!sel)return;sel.innerHTML=cfg.def?'<option value="">'+cfg.def+'</option>':'';var seen={};allUsers.forEach(function(u){var name=u.data.fullName||u.data.email||u.uid;if(cfg.exSelf&&(u.uid===cu.uid||u.data.email===cp.email||(u.data.fullName&&u.data.fullName===cp.fullName)))return;if(seen[name]){if(u.data.role==="volunteer"){var old=sel.querySelector('option[value="'+seen[name]+'"]');if(old)old.value=u.uid;seen[name]=u.uid}return}seen[name]=u.uid;sel.innerHTML+='<option value="'+u.uid+'">'+escapeHTML(name)+'</option>'})})}
async function lh(){document.getElementById("profileCard").innerHTML=rp(cp);var s=await getDocs(query(collection(db,"announcements"),orderBy("createdAt","desc"),limit(3)));document.getElementById("homeAnnouncements").innerHTML=s.empty?'<p class="empty">Duyuru yok.</p>':s.docs.map(function(d){return ra(d.data())}).join("")}
async function lt(){var a=cp.role==="admin"||cp.role==="coordinator";var q=a?query(collection(db,"tasks"),orderBy("createdAt","desc"),limit(50)):query(collection(db,"tasks"),where("assignedToEmail","==",cu.email||""),orderBy("createdAt","desc"),limit(20));var s=await getDocs(q);document.getElementById("tasksList").innerHTML=s.empty?'<p class="empty">Görev bulunamadı.</p>':s.docs.map(function(d){return rt(d.data(),d.id)}).join("")}
async function lr(){var a=cp.role==="admin"||cp.role==="coordinator";rd={};if(a){var q=query(collection(db,"reports"),orderBy("createdAt","desc"),limit(50));var s=await getDocs(q);s.docs.forEach(function(d){rd[d.id]=d.data()});document.getElementById("reportsTitle").textContent="Tüm raporlar"}else{var q1=query(collection(db,"reports"),where("userUid","==",cu.uid),orderBy("createdAt","desc"),limit(20));var q2=query(collection(db,"reports"),where("coworkerUids","array-contains",cu.uid),orderBy("createdAt","desc"),limit(20));var s1=await getDocs(q1);var s2=await getDocs(q2);s1.docs.forEach(function(d){rd[d.id]=d.data()});s2.docs.forEach(function(d){if(!rd[d.id])rd[d.id]=d.data()})}var keys=Object.keys(rd);keys.sort(function(a2,b){var ta=rd[a2].createdAt,tb2=rd[b].createdAt;if(!ta||!tb2)return 0;var da=typeof ta.toMillis==="function"?ta.toMillis():0;var db3=typeof tb2.toMillis==="function"?tb2.toMillis():0;return db3-da});document.getElementById("reportsList").innerHTML=keys.length===0?'<p class="empty">Rapor bulunmuyor.</p>':keys.map(function(id){return rr(rd[id],id)}).join("")}
async function la(){var s=await getDocs(query(collection(db,"announcements"),orderBy("createdAt","desc"),limit(20)));document.getElementById("announcementsList").innerHTML=s.empty?'<p class="empty">Duyuru yok.</p>':s.docs.map(function(d){return ra(d.data())}).join("")}
async function lp(){var s=await getDocs(query(collection(db,"users"),where("status","==","pending"),limit(30)));var el=document.getElementById("pendingUsers");var pt=document.querySelector('[data-tab="pending"]');if(s.empty){el.innerHTML='<p class="empty">Bekleyen başvuru yok.</p>';return}el.innerHTML=s.docs.map(function(d){return rpu(d.data(),d.id)}).join("");if(pt){var x=pt.querySelector(".count-badge");if(x)x.remove();pt.insertAdjacentHTML("beforeend",'<span class="count-badge">'+s.size+'</span>')}}
async function lu(){var s=await getDocs(query(collection(db,"users"),orderBy("createdAt","desc"),limit(100)));document.getElementById("userDirectory").innerHTML=s.empty?'<p class="empty">Kullanıcı bulunamadı.</p>':s.docs.map(function(d){return rur(d.data(),d.id)}).join("")}
function rf(){document.getElementById("reportForm").reset();document.getElementById("editReportId").value="";document.getElementById("hours").value=1;document.getElementById("reportDate").value=td();document.getElementById("reportFormTitle").textContent="Rapor gönder";document.getElementById("reportSubmitBtn").textContent="Rapor gönder";document.getElementById("cancelEditBtn").classList.add("hidden");document.getElementById("reportLinks").value="";var sel=document.getElementById("reportForUser");if(sel)sel.value="";var cw=document.getElementById("reportCoworker");if(cw)Array.from(cw.options).forEach(function(o){o.selected=false});pi=[];uip()}
document.getElementById("cancelEditBtn")?.addEventListener("click",rf);
document.addEventListener("click",async function(e){
var li=e.target.closest(".lightbox-img");if(li){var lb=document.createElement("div");lb.className="lightbox";lb.onclick=function(){lb.remove()};lb.innerHTML='<img src="'+li.src+'"/>';document.body.appendChild(lb);return}
var lbx=e.target.closest(".lightbox");if(lbx){lbx.remove();return}
var apBtn=e.target.closest("[data-approve]");if(apBtn&&db){var rid=apBtn.dataset.approve;var txt=document.querySelector('[data-review-id="'+rid+'"]');var fbText=txt?txt.value.trim():"";var r2=rd[rid];var oldFb=r2&&r2.feedback?r2.feedback:[];var newFb=oldFb.slice();if(fbText)newFb.push({by:cp.fullName||cu.email,date:td(),text:fbText});try{apBtn.disabled=true;apBtn.textContent="...";await updateDoc(doc(db,"reports",rid),{status:"approved",feedback:newFb,reviewerUid:cu.uid,updatedAt:serverTimestamp()});lr()}catch(err){alert("Hata: "+err.message);apBtn.disabled=false;apBtn.textContent="Onayla"}return}
var rvBtn=e.target.closest("[data-revision]");if(rvBtn&&db){var rid2=rvBtn.dataset.revision;var txt2=document.querySelector('[data-review-id="'+rid2+'"]');var fbText2=txt2?txt2.value.trim():"";if(!fbText2){alert("Lütfen düzeltme için geri bildirim yazın.");return}var r3=rd[rid2];var oldFb2=r3&&r3.feedback?r3.feedback:[];var newFb2=oldFb2.slice();newFb2.push({by:cp.fullName||cu.email,date:td(),text:fbText2});try{rvBtn.disabled=true;rvBtn.textContent="...";await updateDoc(doc(db,"reports",rid2),{status:"revision_needed",feedback:newFb2,reviewerUid:cu.uid,updatedAt:serverTimestamp()});lr()}catch(err){alert("Hata: "+err.message);rvBtn.disabled=false;rvBtn.textContent="Düzeltme İste"}return}
var et=e.target.closest("[data-et]");if(et){var tid=et.dataset.et;var tsnap=await getDoc(doc(db,"tasks",tid));if(!tsnap.exists())return;var td2=tsnap.data();document.getElementById("taskTitle").value=td2.title||"";document.getElementById("taskDescription").value=td2.description||"";document.getElementById("taskDepartment").value=td2.department||"";document.getElementById("taskAssignedToEmail").value=td2.assignedToEmail||"";document.getElementById("taskDueDate").value=td2.dueDate||"";document.getElementById("taskPriority").value=td2.priority||"medium";document.getElementById("taskForm").dataset.editId=tid;document.getElementById("taskMessage").textContent="Görevi düzenliyorsunuz...";sw("tasks");document.querySelector("#tab-tasks").scrollIntoView({behavior:"smooth",block:"start"});return}
var dt=e.target.closest("[data-dt]");if(dt&&db){if(!confirm("Bu görevi silmek istediğinize emin misiniz?"))return;try{dt.disabled=true;dt.textContent="...";await deleteDoc(doc(db,"tasks",dt.dataset.dt));lt()}catch(err){alert("Hata: "+err.message);dt.disabled=false;dt.textContent="Sil"}return}
var eb=e.target.closest("[data-er]");if(eb){var id=eb.dataset.er,r=rd[id];if(!r)return;document.getElementById("editReportId").value=id;document.getElementById("taskId").value=r.taskId||"";document.getElementById("reportDate").value=r.reportDate||"";document.getElementById("hours").value=r.hours||1;document.getElementById("summary").value=r.summary||"";document.getElementById("reportLinks").value=(r.links||[]).join("\n");var sel=document.getElementById("reportForUser");if(sel){var targetUid=r.userUid||"";sel.value=targetUid===cu.uid?"":targetUid}setSelectedValues("reportCoworker",r.coworkerUids||[]);pi=(r.images||[]).slice();uip();document.getElementById("reportFormTitle").textContent="Raporu düzenle";document.getElementById("reportSubmitBtn").textContent="Güncelle";document.getElementById("cancelEditBtn").classList.remove("hidden");document.querySelector("#tab-reports").scrollIntoView({behavior:"smooth",block:"start"});return}
var db2=e.target.closest("[data-dr]");if(db2&&db){if(!confirm("Bu raporu silmek istediğinize emin misiniz?"))return;try{db2.disabled=true;db2.textContent="...";await deleteDoc(doc(db,"reports",db2.dataset.dr));lr()}catch(err){alert("Hata: "+err.message);db2.disabled=false;db2.textContent="Sil"}return}
var ri=e.target.closest("[data-ri]");if(ri){pi.splice(Number(ri.dataset.ri),1);uip();return}
var ab=e.target.closest("button[data-action]");if(ab&&db){try{ab.disabled=true;ab.textContent="...";await updateDoc(doc(db,"users",ab.dataset.uid),{status:ab.dataset.action==="approve"?"approved":"blocked",updatedAt:serverTimestamp()});var cd=document.getElementById("user-"+ab.dataset.uid);if(cd){cd.style.opacity="0.4";cd.innerHTML='<div class="user-info"><strong>'+(ab.dataset.action==="approve"?"Onaylandı":"Engellendi")+'</strong></div>'}}catch(err){alert("Hata: "+err.message);ab.disabled=false}return}
var sv=e.target.closest("button[data-sv]");if(sv&&db){var uid=sv.dataset.sv,row=document.getElementById("urow-"+uid);try{sv.disabled=true;sv.textContent="...";await updateDoc(doc(db,"users",uid),{fullName:row.querySelector('[data-fn="'+uid+'"]').value.trim(),email:row.querySelector('[data-em="'+uid+'"]').value.trim(),phone:row.querySelector('[data-ph="'+uid+'"]').value.trim(),department:row.querySelector('[data-dp="'+uid+'"]').value,role:row.querySelector('[data-ru="'+uid+'"]').value,status:row.querySelector('[data-su="'+uid+'"]').value,updatedAt:serverTimestamp()});sv.textContent="OK";setTimeout(function(){sv.textContent="Kaydet";sv.disabled=false},1500)}catch(err){alert("Hata: "+err.message);sv.textContent="Kaydet";sv.disabled=false}return}
var du=e.target.closest("button[data-del-user]");if(du&&db){var duid=du.dataset.delUser;if(!confirm("Bu kullanıcıyı silmek istediğinize emin misiniz?"))return;try{du.disabled=true;du.textContent="...";await deleteDoc(doc(db,"users",duid));var drow=document.getElementById("urow-"+duid);if(drow)drow.remove()}catch(err){alert("Hata: "+err.message);du.disabled=false;du.textContent="Sil"}return}
});
document.getElementById("reportForm")?.addEventListener("submit",async function(e){e.preventDefault();if(!cu||!db)return;var eid=document.getElementById("editReportId").value;var selUser=document.getElementById("reportForUser");var targetUid=selUser&&selUser.value?selUser.value:cu.uid;var targetUser=allUsers.find(function(u){return u.uid===targetUid});var targetEmail=targetUser?targetUser.data.email||"":cu.email||"";var cwUids=getSelectedValues("reportCoworker");var data={taskId:document.getElementById("taskId").value.trim(),summary:document.getElementById("summary").value.trim(),hours:Number(document.getElementById("hours").value||0),reportDate:document.getElementById("reportDate").value,links:pl(document.getElementById("reportLinks").value),images:pi.slice(),coworkerUids:cwUids,updatedAt:serverTimestamp()};try{if(eid){data.status="submitted";await updateDoc(doc(db,"reports",eid),data);document.getElementById("reportMessage").textContent="Rapor güncellendi!"}else{data.userUid=targetUid;data.userEmail=targetEmail;data.status="submitted";data.reviewerUid=null;data.feedback=[];data.createdAt=serverTimestamp();await addDoc(collection(db,"reports"),data);document.getElementById("reportMessage").textContent="Rapor kaydedildi!"}rf();setTimeout(function(){document.getElementById("reportMessage").textContent=""},3000);lr()}catch(err){document.getElementById("reportMessage").textContent="Hata: "+err.message}});
document.getElementById("taskForm")?.addEventListener("submit",async function(e){e.preventDefault();if(!cu||!db)return;var eid=e.target.dataset.editId||"";var data={title:document.getElementById("taskTitle").value.trim(),description:document.getElementById("taskDescription").value.trim(),department:document.getElementById("taskDepartment").value,assignedToUid:null,assignedToEmail:document.getElementById("taskAssignedToEmail").value.trim(),dueDate:document.getElementById("taskDueDate").value||null,priority:document.getElementById("taskPriority").value,status:"open",updatedAt:serverTimestamp()};try{if(eid){await updateDoc(doc(db,"tasks",eid),data);document.getElementById("taskMessage").textContent="Görev güncellendi!";delete e.target.dataset.editId}else{data.createdByUid=cu.uid;data.createdAt=serverTimestamp();await addDoc(collection(db,"tasks"),data);document.getElementById("taskMessage").textContent="Görev oluşturuldu!"}e.target.reset();setTimeout(function(){document.getElementById("taskMessage").textContent=""},3000);lt()}catch(err){document.getElementById("taskMessage").textContent="Hata: "+err.message}});
document.getElementById("addUserForm")?.addEventListener("submit",async function(e){e.preventDefault();if(!cu||!db)return;var em=document.getElementById("addUserEmail").value.trim().toLowerCase();var userData={email:em,fullName:document.getElementById("addUserName").value.trim(),department:document.getElementById("addUserDepartment").value,role:document.getElementById("addUserRole").value,phone:document.getElementById("addUserPhone").value.trim(),status:"approved",notes:"",uid:"manual_"+em,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()};try{await setDoc(doc(db,"users","manual_"+em),userData);await setDoc(doc(db,"preregistered",em),{email:em,fullName:userData.fullName,department:userData.department,role:userData.role,phone:userData.phone,status:"approved",createdByUid:cu.uid,createdAt:serverTimestamp()});e.target.reset();document.getElementById("addUserMessage").textContent="Kullanıcı eklendi!";setTimeout(function(){document.getElementById("addUserMessage").textContent=""},3000);lu()}catch(err){document.getElementById("addUserMessage").textContent="Hata: "+err.message}});
document.getElementById("announcementForm")?.addEventListener("submit",async function(e){e.preventDefault();if(!cu||!db)return;try{await addDoc(collection(db,"announcements"),{title:document.getElementById("announcementTitle").value.trim(),body:document.getElementById("announcementBody").value.trim(),audience:document.getElementById("announcementAudience").value,department:"",createdByUid:cu.uid,createdAt:serverTimestamp()});e.target.reset();document.getElementById("announcementMessage").textContent="Duyuru yayınlandı!";setTimeout(function(){document.getElementById("announcementMessage").textContent=""},3000);la()}catch(err){document.getElementById("announcementMessage").textContent="Hata: "+err.message}});
if(!auth||!db){ld.innerHTML='<p class="empty">'+missingConfigMessage+'</p>'}else{onAuthStateChanged(auth,async function(user){if(!user){window.location.href="../auth/";return}cu=user;var s=await getDoc(doc(db,"users",user.uid));if(!s.exists()||s.data().status!=="approved"){window.location.href="../auth/";return}cp=s.data();var isA=cp.role==="admin"||cp.role==="coordinator";hu.textContent=cp.fullName||user.email;if(isA){document.querySelectorAll(".admin-tab").forEach(function(t){t.classList.remove("hidden")});document.getElementById("adminTaskForm")?.classList.remove("hidden");document.getElementById("adminAnnouncementForm")?.classList.remove("hidden");document.getElementById("reportUserRow")?.classList.remove("hidden")}await loadAllUsers();document.getElementById("reportDate").value=td();ld.classList.add("hidden");tb.classList.remove("hidden");await lh();lt();lr();la();if(isA){lp();lu()}})}

